function l = names()
l = {'tipmas', 'snom', 'cosnom', 'pnom', 'un', 'ifaz', 'fn', 'obmin', ...
    'n2p', 'ce', 'tau', 'di', 'da', 'ks', 'elt', 'el', 'elef', ...
    'del', 'ef', 'nr', 'brad', 'qa', 'ha', 'ha1', 'la', 'npaz', ...
    't', 't3', 't2', 'bc', 'bcspec', 'bz', 'bz13', 'bz12', 'b1', ...
    'h', 'h1', 'qz3', 'qz2', 'cd', 'i1', 'ia', 'jja', 'nss', 'w', ... 
    'a', 'ela', 'els', 'as', 'ao', 'bo', 'ai', 'bi', 'ra15', ...
    'ra75', 'no', 'qo', 'y', 'bet', 'fq', 'ksk', 'fbet', 'fw', ...
    'delta', 'delmax', 'd1', 'delmm', 'alm', 'elo', 'al', 'qdel', ...
    'dbash', 'rp', 'taum', 'hp', 'bp', 'bp1', 'elp', 'elu', 'hm', ...
    'bm', 'elm', 'elm1', 'elf', 'qm', 'we', 'pje', 'ae', 'aeo', ...
    'ele', 'qe', 'be1', 'be', 'beo', 'besum', 're15', 're75', 'nb', ...
    'not', 'ddemot', 't2ot', 'hs', 'bs', 'nz', 'ddemz', 't2zak', ...
    'hsz', 'elb', 'elb1', 'qb', 'qbz', 'cgb', 'ar', 'br', 'qr', ...
    'cr', 'fkf', 'aklam', 'dkd1', 'dkd2', 'dkd3', 'dkd', 'ap', ...
    'dt', 'cp', 'lampl', 'lamml', 'lammb', 'lammp', 'lamsig', ...
    'xp', 'xp1', 'fi1n', 'fin', 'filamn', 'uftn', 'bdeln', ...
    'bz3n', 'ban', 'awzn', 'awan', 'sigmn', 'sigpn', 'bmin', ... 
    'bpin', 'bm12n', 'awt1n', 'awt3n', 'awt2n', 'awmn', 'awdn', ...
    'awzwn', 'awawn', 'awmwn', 'awcn', 'awjn', 'awsumn', ...
    'hhin', 'uuf', 'kad', 'kaq', 'bs1', 'lamot',...
    'lamz', 'lamsr', 'rast', 'r1', 'r2', 'rf', 'rkd', 'rkq', 'xl', ...
    'xad', 'xaq', 'xd', 'xq', 'xf', 'xfras', 'xd1', 'xkd', 'xkq', ...
    'xd2p', 'xq2p', 'x2', 'x0', 'td01', 'td1', 'ta', 'tc01', ...
    'td02', 'td2', 'tq01', 'tq2', 'okz', 'stover', 'terdem', ...
    'c3f', 'c1f', 'crot', 'qczar', 'pqa', 'pqz', 'pqp0', 'pqt', ...
    'pqc', 'pqfehh', 'pqv', 'raswoz', 'tetwoz', 'pqpodp', 'qwpp', ...
    'grt', 'fpp', 'qwps', 'pqpost', 'kvd', 'pqmed', 'pqf', ...
    'pqtkz', 'pkzkvd', 'pqpz', 'pqph', 'pqed', 'pqdob', 'pqkz', ...
    'b3', 'a3m', 'a30', 'fildk', 'gkc', 'gks', 'pqwed', 'pqsed', ...
    'pqpol', 'kpdd', 'ga', 'gz', 'gs', 'gus', 'gps', 'gc', 'gc1', ...
    'gce', 'gm', 'gum', 'gpm', 'giz', 'gb', 'gr', 'gd', 'wfe', ...
    'wcu', 'wi', 'teti', 'tetfe', 'tets', 'tetcu', 'wcu2', 'tetep'};
end